export default Object.freeze({
    FILL_TODOS: 'FILL_TODOS',

    CLEAR_TODOS: 'CLEAR_TODOS',

    FETCH_TODOS:         'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAIL:    'FETCH_TODOS_FAIL',

    CREATE_TODO:         'CREATE_TODO',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_TODO_FAIL:    'CREATE_TODO_FAIL',

    CHANGE_PRIORITY: 'CHANGE_PRIORITY',

    COMPLETE: 'COMPLETE',

    COMPLETE_ALL: 'COMPLETE_ALL',

    UPDATE_TODO:         'UPDATE_TODO',
    UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
    UPDATE_TODO_FAIL:    'UPDATE_TODO_FAIL',

    DELETE_TODO:         'DELETE_TODO',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAIL:    'DELETE_TODO_FAIL',
});
